images:
- gcr.io/fuzzbench/base-image:test-experiment
- gcr.io/fuzzbench/base-image
- gcr.io/fuzzbench/base-builder-new:test-experiment
- gcr.io/fuzzbench/base-builder-new
steps:
- args:
  - build
  - --tag
  - gcr.io/fuzzbench/base-image:test-experiment
  - --tag
  - gcr.io/fuzzbench/base-image
  - --tag
  - gcr.io/fuzzbench/base-image
  - --cache-from
  - gcr.io/fuzzbench/base-image
  - --build-arg
  - BUILDKIT_INLINE_CACHE=1
  - --file
  - docker/base-image/Dockerfile
  - .
  env:
  - DOCKER_BUILDKIT=1
  id: base-image
  name: gcr.io/cloud-builders/docker
  wait_for: []
- args:
  - build
  - --tag
  - gcr.io/fuzzbench/base-builder-new:test-experiment
  - --tag
  - gcr.io/fuzzbench/base-builder-new
  - --tag
  - gcr.io/fuzzbench/base-builder-new
  - --cache-from
  - gcr.io/fuzzbench/base-builder-new
  - --build-arg
  - BUILDKIT_INLINE_CACHE=1
  - --file
  - docker/base-builder-new/Dockerfile
  - .
  env:
  - DOCKER_BUILDKIT=1
  id: base-builder-new
  name: gcr.io/cloud-builders/docker
  wait_for: []
tags:
- test-experiment
